### ISSUE TITLE
getupcomingbroadcast 404

### ISSUE THREAD

**Issue by AlexanderKozhevin** [GoodGame/API#17]
В доках указан метод. 
```
http://goodgame.ru/api/getupcomingbroadcast
```
Но он отдает 404, даже передаю access_token и все параметры. 
Тоже самое тут
```
http://api2.goodgame.ru/getupcomingbroadcast
```

![Screenshot 2019-06-05 at 16 33 23](https://user-images.githubusercontent.com/4464561/58960340-ae037700-87af-11e9-8593-b23892fb8685.png)

**Comment by AlexanderKozhevin** [comment]
@yugeon Добрый день. Не могли бы вы помочь?

**Comment by MaximKulikov** [comment]
На их форуме были темы про API, попробуйте там узнать.

**Comment by WiFi-3** [comment]
Но все равно getupcomingbroadcast удален из Api, Api2 устарело, воспользуйтесь Api4 https://goodgame.ru/help/5/53
