### ISSUE TITLE
Не работает API

### ISSUE THREAD

**Issue by rekmixa** [GoodGame/API#18]
Все API-методы не работают. Пожалуйста, пофиксите)

Fatal error: Uncaught Zend\ModuleManager\Exception\RuntimeException: Module (ZF\DevelopmentMode) could not be initialized. in /home/goodgame/var/www/goodgame.ru/protected/libs/vendor/zendframework/zend-modulemanager/src/ModuleManager.php:201 Stack trace: #0 /home/goodgame/var/www/goodgame.ru/protected/libs/vendor/zendframework/zend-modulemanager/src/ModuleManager.php(173): Zend\ModuleManager\ModuleManager->loadModuleByName(Object(Zend\ModuleManager\ModuleEvent)) #1 /home/goodgame/var/www/goodgame.ru/protected/libs/vendor/zendframework/zend-modulemanager/src/ModuleManager.php(95): Zend\ModuleManager\ModuleManager->loadModule('ZF\\DevelopmentM...') #2 /home/goodgame/var/www/goodgame.ru/protected/libs/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\ModuleManager\ModuleManager->onLoadModules(Object(Zend\ModuleManager\ModuleEvent)) #3 /home/goodgame/var/www/goodgame.ru/protected/libs/vendor/zendframework/zend-eventmanager/src/EventManager.php(171): Zend\EventManager\EventManager->triggerListeners(Object( in /home/goodgame/var/www/goodgame.ru/protected/libs/vendor/zendframework/zend-modulemanager/src/ModuleManager.php on line 201

http://api2.goodgame.ru/apigility/documentation

**Comment by Mirimas** [comment]
+1 я писал об этом на почту саппорта 11 июля, ответили что посмотрят, но когда исправят не понятно.

**Comment by WiFi-3** [comment]
Пофикшено, проверяйте.
