### ISSUE TITLE
Устарело описание API чата.

### ISSUE THREAD

**Issue by ExC0tiC** [GoodGame/API#5]
Устарело описание API чата.
1) Для получения списка пользователей на канале необходимо отправлять type:get_users_list2 , а не type:get_users_list
2) Не описаны многие запросы к серверу, может быть специально, а может быть и нет.:
create_room - полностью
get_random - полностью
get_stream_moders_list - полностью
в join не описан параметр mobile
в get_channel_history не описан параметр from
в send_private_message не описаны параметры username, color, icon, mobile (они служебные?)
в send_message не описаны параметры color, icon, mobile . Похоже что вместо icon описан hideIcon
setting - полностью

**Comment by SG5** [comment]
В методе ```get_channels_list``` указано что ```clients_in_channel``` будет числом, а возвращается строкой.
